language: scala
scala:
   - 2.10.6
   - 2.11.5
jdk:
  - oraclejdk7
  - oraclejdk8
script:
  - sbt test
deploy:
  skip_cleanup: true
  provider: script
  script: ./.travis/deploy.sh $TRAVIS_TAG
  on:
    condition: '"${TRAVIS_SCALA_VERSION}" == "2.10.6" && "${TRAVIS_JDK_VERSION}" == "oraclejdk8"' 
    tags: true
