language: scala
scala:
   - 2.10.6
   - 2.11.5
jdk:
  - oraclejdk7
  - oraclejdk8
script:
  - sbt test
script:
  - sbt test
deploy:
  skip_cleanup: true
  provider: script
  script: ./.travis/deploy.sh $TRAVIS_TAG
  on:
    condition: '"${TRAVIS_SCALA_VERSION}" == "2.10.6" && "${TRAVIS_JDK_VERSION}" == "oraclejdk8"' 
    tags: true
env:
  global:
  # BINTRAY_SNOWPLOW_MAVEN_USER
  - secure: qETDQd6Z9R/LAV3Kijz3bZlyYJT8RV60PsfquhAk1714ztnBDXkVspPyGdrupmUOfE87ieUoZGx2h3kQvvgNPnx5AKcJZQZGQiHm817TcmdUOeiECPAOk5u3I3t/03qv7J/9yckss7degLEwX5mnJtKYE2Ao+2DZ18xUArTXMzh2k+DFsBSDqZoIyEeUAss2ZE+IQXsMxdniTccXwtAjrPPE56c9H2EXEX6mgpcc5xm80n5m5YhFUMT7hu5Amrgmn4KzfYVCoaqFFCky78I3W+hlhNsOtrcN6TC+seV5mcIbvu679G0mKsaVCQp4kJKFF9sevDoPC8RUyDUhWvlALxO+5++fr0brx3Dy+/x5zVgU+VbraKtq30qhNe8ssHnUrz9w77uwHAeKPM9o1VNN12fOejlJiFtvNYoDKTYKm/pQRGH3nDuLAmSsKcKBqCYUAR4kIgW4m75pAy/M5jmMUgAKRKvVaUhi5yc+gQunmTRdFOm9iEleOutERJQGGN+3/97KcaaMDCDw1qv+X901PPkgOKoc+c0TvIGG+pw+K1FcBzpFd1UPxVo8EgWN9WcYNQX1Y8IKCEJ5nt7EV1rTl+NZy7eF1beuhGzMfFpGTpmGLNdV5APRn23kVGBGbuN9oQmsqqNp6w2BXISrT7wI2jBXiLbTEb9Fm4dn6zwj5ao=
  # BINTRAY_SNOWPLOW_MAVEN_API_KEY
  - secure: a3IR33P9048TbBZ4DXnNXRv6J5Ugb6JIfc51ixFKpR7IBuuAPsSmkaJCbIgkgxkaMBCCmP6UTMoY3RRe449IrUH/x+WHLD5P7hNo0D0rGBh96Hu8EVIqSnPmpuYLmm3llEkXgKhje5spLw9af1VKzVe89V7vo4o2OFkv16eymDgs8ftC7NHTH9bPuBVKFZgmbfXtWTHwBMDp1t/zWlFTcfDXVf2IkXlFYTk9BioRsunk8MRk1gRAbhWibgZeGDo8N90ZK0pvNaU5oPzjblWaPCYmBsXkZT27wkUOBEmv78Fh9Y1LUmQNBs203zezGTSOa5zIZkpvmzY42jd8bQY9LSfArPH3Pe0NbpGjUJoySItd3ONcYngf7hY5Z9eqjWVbvkeRSbU0ysWLJtxrw2Uy34oxbOfrkh86KZhihd0iyfaKQUr5ldag+T5pqHlWrC21h/QevD2rhx5uPgAkyLdy4Mqmoeoe1p/aOFi8jK9mvET6Ie4yMzdwwEnZBL3EjuzSpBYSghMQrJntwc1Jx5PSpCNcK9CTjO/dn5nTKaq4VhABihCwezlH47+vhgChOff3cMDzLSOjvWzX7EpaMylKd0GvlUCzdezZgtqLfj0ue3zuWs/VEPUYmp7ukQWKxhMQcLTKnR/2xu4gZvdqO17jPIwRQz1EzV3pqJgKmHCD6x4=